# permissions for end users to edit streamservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: streamserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netagent
    app.kubernetes.io/part-of: netagent
    app.kubernetes.io/managed-by: kustomize
  name: streamserver-editor-role
rules:
- apiGroups:
  - crd.chulinx
  resources:
  - streamservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.chulinx
  resources:
  - streamservers/status
  verbs:
  - get
