# permissions for end users to view streamservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: streamserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netagent
    app.kubernetes.io/part-of: netagent
    app.kubernetes.io/managed-by: kustomize
  name: streamserver-viewer-role
rules:
- apiGroups:
  - crd.chulinx
  resources:
  - streamservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.chulinx
  resources:
  - streamservers/status
  verbs:
  - get
